<?php
$_product = $this->getProduct();
$preco = $_product->getFinalPrice();
$desconto = Mage::getData('desconto');
$precoDesc = $preco * (1 - ($desconto/100));
 echo 'ou '.Mage::helper('core')->currency($precoDesc);
?>

<script type="text/javascript">
//<![CDATA[
var $j = jQuery.noConflict();
$j(document).ready(function(){
$j(".input-box select").change(function(){
$j('#desconto').html('<img src="<?php echo $this->getSkinUrl('images/kaury_desconto/ajax-loader.gif'); ?>"> Carregando');
$j.ajax({
url: '<?php echo $this->getUrl("desconto")?>',
type:"POST",
data:({"preco": $j('.price-box span span.price').html()}),
success: function(data) {
$j('#desconto').html(data);
}
})
})
})
//]]>
</script>
